"""Report formatters — terminal (rich), JSON, and Markdown output."""

from __future__ import annotations

import json as _json

from mygo.models import Report

SEVERITY_COLORS = {
    "critical": "red",
    "major": "yellow",
    "minor": "blue",
    "suggestion": "dim",
}

SEVERITY_ORDER = {"critical": 1, "major": 2, "minor": 3, "suggestion": 4}


def format_json(report: Report) -> str:
    """Return a JSON string of the full report."""
    return _json.dumps(report.to_dict(), indent=2, ensure_ascii=False)


def format_markdown(report: Report) -> str:
    """Return a Markdown representation of the report."""
    lines: list[str] = []
    lines.append("# Code Review Report")
    lines.append("")
    lines.append(f"**Score**: {report.score}/100 | **Files**: {report.metadata.files_reviewed} | "
                  f"**Model**: {report.metadata.model} | **Duration**: {report.metadata.duration_ms}ms")
    lines.append("")
    lines.append("## Summary")
    lines.append(report.summary)
    lines.append("")

    if report.findings:
        lines.append("## Findings")
        lines.append("")
        for f in sorted(report.findings, key=lambda x: SEVERITY_ORDER.get(x.severity, 99)):
            emoji = {"critical": "🔴", "major": "🟡", "minor": "🔵", "suggestion": "⚪"}[f.severity]
            location = f"{f.file}:{f.line}" if f.line else f.file
            lines.append(f"### {emoji} [{f.severity.upper()}] {f.title}")
            lines.append("")
            lines.append(f"- **Category**: {f.category}")
            lines.append(f"- **Location**: `{location}`")
            lines.append(f"- **Description**: {f.description}")
            if f.suggestion:
                lines.append(f"- **Suggestion**: {f.suggestion}")
            lines.append("")

    lines.append(f"---")
    lines.append(f"*Report generated by MyGO*")
    return "\n".join(lines)


def format_terminal(report: Report) -> str:
    """Return a Rich-styled terminal representation.

    Imported lazily so the ``rich`` dependency is only required for
    terminal output, not for JSON or Markdown modes.
    """
    from rich.console import Console, Group
    from rich.panel import Panel
    from rich.table import Table
    from rich.text import Text
    from rich import box

    console = Console(no_color=False, width=100)

    # Score panel
    score_color = "green" if report.score >= 80 else "yellow" if report.score >= 60 else "red"
    score_text = Text(f"Score: {report.score}/100", style=f"bold {score_color}")
    summary_text = Text(report.summary, style="dim")
    header = Group(score_text, Text(""), summary_text)

    # Findings table
    table = Table(box=box.ROUNDED, show_header=True, header_style="bold")
    table.add_column("Severity", style="bold", width=10)
    table.add_column("Category", width=12)
    table.add_column("Location", width=18, style="dim")
    table.add_column("Title")
    table.add_column("Description")

    for f in sorted(report.findings, key=lambda x: SEVERITY_ORDER.get(x.severity, 99)):
        style = SEVERITY_COLORS.get(f.severity, "")
        location = f"{f.file}:{f.line}" if f.line else f.file
        table.add_row(
            f.severity.upper(), f.category, location, f.title, f.description[:120],
            style=style,
        )

    # Metadata footer
    meta = Text(
        f"Model: {report.metadata.model} | "
        f"Files: {report.metadata.files_reviewed} | "
        f"LSP symbols: {report.metadata.lsp_symbols_queried} | "
        f"Context modules: {report.metadata.context_modules_matched} | "
        f"Duration: {report.metadata.duration_ms}ms | "
        f"Tokens: {report.metadata.tokens_used}",
        style="dim italic",
    )

    # Build a capture-compatible output
    with console.capture() as capture:
        console.print(Panel(header, title="Code Review Report", border_style="blue"))
        if report.findings:
            console.print(table)
        else:
            console.print(Text("No findings — code looks good!", style="green"))
        console.print(meta)

    return capture.get()
